# Generated by Django 4.2.8 on 2023-12-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_remove_orderitem_item_orderitem_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
